version: "3.9"

services:
  # nginx:
  #   restart: always
  #   image: nginx:1.22
  #   volumes:
  #     - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   links:
  #     - backend:backend
  #   ports:
  #     - "80:80"
  #     - "443:443"

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata user_data.json &&
             python manage.py collectstatic --noinput &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8080"
    environment:
      - PROJECT_NAME=App
      - SECRET_KEY=change-me
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  postgres-data: